"""Constants shared by anomaly-infra core and integrations."""

ANOMALY_DETECTION_ENABLED = "ANOMALY_DETECTION_ENABLED"
ANOMALY_ALERTING_ENABLED = "ANOMALY_ALERTING_ENABLED"
ANOMALY_BLOCKING_ENABLED = "ANOMALY_BLOCKING_ENABLED"

ANOMALY_RULE_BURST_ENABLED = "ANOMALY_RULE_BURST_ENABLED"
ANOMALY_RULE_PERMISSION_PROBING_ENABLED = "ANOMALY_RULE_PERMISSION_PROBING_ENABLED"
ANOMALY_RULE_BUSINESS_TAMPERING_ENABLED = "ANOMALY_RULE_BUSINESS_TAMPERING_ENABLED"
ANOMALY_RULE_CROSS_TENANT_ENABLED = "ANOMALY_RULE_CROSS_TENANT_ENABLED"

CATEGORY_REQUEST = "request"
CATEGORY_PERMISSION = "permission"
CATEGORY_BUSINESS = "business"
VALID_CATEGORIES = frozenset({CATEGORY_REQUEST, CATEGORY_PERMISSION, CATEGORY_BUSINESS})

SEVERITY_LOW = "low"
SEVERITY_MEDIUM = "medium"
SEVERITY_HIGH = "high"
SEVERITY_CRITICAL = "critical"
VALID_SEVERITIES = frozenset(
    {SEVERITY_LOW, SEVERITY_MEDIUM, SEVERITY_HIGH, SEVERITY_CRITICAL}
)

ALERT_THRESHOLD = 50
STEP_UP_THRESHOLD = 80
BLOCK_THRESHOLD = 100

MASKED_VALUE = "***"
