from dataclasses import dataclass

ANOMALY_DETECTION_ENABLED = "ANOMALY_DETECTION_ENABLED"
ANOMALY_ALERTING_ENABLED = "ANOMALY_ALERTING_ENABLED"
ANOMALY_BLOCKING_ENABLED = "ANOMALY_BLOCKING_ENABLED"

ANOMALY_RULE_BURST_ENABLED = "ANOMALY_RULE_BURST_ENABLED"
ANOMALY_RULE_PERMISSION_PROBING_ENABLED = "ANOMALY_RULE_PERMISSION_PROBING_ENABLED"
ANOMALY_RULE_BUSINESS_TAMPERING_ENABLED = "ANOMALY_RULE_BUSINESS_TAMPERING_ENABLED"
ANOMALY_RULE_CROSS_TENANT_ENABLED = "ANOMALY_RULE_CROSS_TENANT_ENABLED"

CATEGORY_REQUEST = "request"
CATEGORY_PERMISSION = "permission"
CATEGORY_BUSINESS = "business"

SEVERITY_LOW = "low"
SEVERITY_MEDIUM = "medium"
SEVERITY_HIGH = "high"
SEVERITY_CRITICAL = "critical"

ALERT_THRESHOLD = 50
STEP_UP_THRESHOLD = 80
BLOCK_THRESHOLD = 100


@dataclass(frozen=True)
class RuleProfile:
    risk_score: int
    severity: str
    category: str


RULE_PROFILES = {
    "invoice_amount_paid_tampering": RuleProfile(90, SEVERITY_CRITICAL, CATEGORY_BUSINESS),
    "repeated_validation_failures": RuleProfile(10, SEVERITY_LOW, CATEGORY_REQUEST),
    "repeated_forbidden_access": RuleProfile(20, SEVERITY_MEDIUM, CATEGORY_PERMISSION),
    "cross_tenant_access_attempt": RuleProfile(50, SEVERITY_HIGH, CATEGORY_PERMISSION),
    "burst_sensitive_endpoint_access": RuleProfile(60, SEVERITY_HIGH, CATEGORY_REQUEST),
    "invoice_total_mismatch": RuleProfile(70, SEVERITY_HIGH, CATEGORY_BUSINESS),
    "invalid_invoice_status_transition": RuleProfile(80, SEVERITY_CRITICAL, CATEGORY_BUSINESS),
    "stock_underflow_attempt": RuleProfile(75, SEVERITY_HIGH, CATEGORY_BUSINESS),
    "duplicate_submission_pattern": RuleProfile(45, SEVERITY_MEDIUM, CATEGORY_REQUEST),
}

DEFAULT_RULE_PROFILE = RuleProfile(30, SEVERITY_MEDIUM, CATEGORY_REQUEST)